In [1]:
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
sns.set()
import warnings
warnings.filterwarnings('ignore')

In [2]:
df=pd.read_csv('Score.csv')
df.head()

Delay_from_due_date  Num_of_Delayed_Payment  Num_Credit_Inquiries  \
0                  3.0                     7.0                   4.0   
1                  3.0                     7.0                   4.0   
2                  3.0                     7.0                   4.0   
3                  5.0                     4.0                   4.0   
4                  6.0                     4.0                   4.0   

   Credit_Utilization_Ratio  Credit_History_Age Payment_of_Min_Amount  \
0                 26.822620               265.0                    No   
1                 31.944960               265.0                    No   
2                 28.609352               267.0                    No   
3                 31.377862               268.0                    No   
4                 24.797347               269.0                    No   

   Amount_invested_monthly  Monthly_Balance Credit_Score Credit_Mix  ...  \
0                80.415295       312.494089         Good       Good  ...   
1               118.280222       284.629162         Good       Good  ...   
2                81.699521       331.209863         Good       Good  ...   
3               199.458074       223.451310         Good       Good  ...   
4                41.420153       341.489231         Good       Good  ...   

    Age  Annual_Income  Num_Bank_Accounts  Num_Credit_Card  Interest_Rate  \
0  23.0       19114.12                3.0              4.0            3.0   
1  23.0       19114.12                3.0              4.0            3.0   
2  23.0       19114.12                3.0              4.0            3.0   
3  23.0       19114.12                3.0              4.0            3.0   
4  23.0       19114.12                3.0              4.0            3.0   

   Num_of_Loan  Monthly_Inhand_Salary  Changed_Credit_Limit  Outstanding_Debt  \
0          4.0            1824.843333                 11.27            809.98   
1          4.0            1824.843333                 11.27            809.98   
2          4.0            1824.843333                 11.27            809.98   
3          4.0            1824.843333                 11.27            809.98   
4          4.0            1824.843333                 11.27            809.98   

   Total_EMI_per_month  
0            49.574949  
1            49.574949  
2            49.574949  
3            49.574949  
4            49.574949  

[5 rows x 21 columns]

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99960 entries, 0 to 99959
Data columns (total 21 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Delay_from_due_date       99960 non-null  float64
 1   Num_of_Delayed_Payment    99960 non-null  float64
 2   Num_Credit_Inquiries      99960 non-null  float64
 3   Credit_Utilization_Ratio  99960 non-null  float64
 4   Credit_History_Age        99960 non-null  float64
 5   Payment_of_Min_Amount     99960 non-null  object 
 6   Amount_invested_monthly   99960 non-null  float64
 7   Monthly_Balance           99960 non-null  float64
 8   Credit_Score              99960 non-null  object 
 9   Credit_Mix                99960 non-null  object 
 10  Payment_Behaviour         99960 non-null  object 
 11  Age                       99960 non-null  float64
 12  Annual_Income             99960 non-null  float64
 13  Num_Bank_Accounts         99960 non-null  float64
 14  Num_Cr

In [4]:
df.duplicated().sum()

0

In [5]:
df.isnull().sum()

Delay_from_due_date         0
Num_of_Delayed_Payment      0
Num_Credit_Inquiries        0
Credit_Utilization_Ratio    0
Credit_History_Age          0
Payment_of_Min_Amount       0
Amount_invested_monthly     0
Monthly_Balance             0
Credit_Score                0
Credit_Mix                  0
Payment_Behaviour           0
Age                         0
Annual_Income               0
Num_Bank_Accounts           0
Num_Credit_Card             0
Interest_Rate               0
Num_of_Loan                 0
Monthly_Inhand_Salary       0
Changed_Credit_Limit        0
Outstanding_Debt            0
Total_EMI_per_month         0
dtype: int64

In [6]:
for i in df.columns:
    print('*************',i,'***********')
    print()
    print(set(df[i].tolist()))

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



{65536.74, 65538.64, 32772.29, 65544.12, 32777.51, 98313.12, 163851.12, 131080.8, 32776.72, 131091.12, 131091.6, 65558.36, 98330.8, 32795.94, 32808.09, 131113.28, 32810.76, 32812.59, 131121.75, 65586.32, 65588.1, 32825.81, 32827.08, 32827.25, 32829.62, 65598.44, 65599.92, 163904.56, 32835.4, 32835.91, 32842.44, 32853.95, 32854.74, 32853.06, 131165.24, 65630.66, 65635.12, 32871.96, 32875.17, 65644.4, 32876.7, 32881.92, 32889.64, 131199.12, 32897.91, 32900.5, 32901.79, 98436.6, 65671.98, 32904.13, 65668.78, 163978.4, 32908.26, 65677.38, 32910.92, 32919.12, 98455.26, 98459.7, 32928.36, 32928.14, 131235.75, 32933.44, 32937.83, 32943.66, 65714.32, 32946.22, 131253.81, 131254.8, 32955.92, 164027.12, 32959.87, 98495.8, 65735.46, 32967.94, 32971.85, 32972.8, 98509.71, 131282.91, 98518.68, 32985.87, 32989.45, 32991.92, 131296.92, 32995.78, 98534.22, 33000.46, 33002.23, 98544.99, 131313.4, 65778.22, 33012.39, 33022.7, 33022.95, 65793.66, 33029.66, 33030.03, 33032.46, 65804.68, 33036.44, 65806.24

In [7]:
categorical=['Payment_of_Min_Amount','Credit_Score','Credit_Mix','Payment_Behaviour']
categorical

['Payment_of_Min_Amount', 'Credit_Score', 'Credit_Mix', 'Payment_Behaviour']

In [8]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [9]:
for columns in categorical:
    df[columns]=le.fit_transform(df[columns])

In [10]:
df.head()

Delay_from_due_date  Num_of_Delayed_Payment  Num_Credit_Inquiries  \
0                  3.0                     7.0                   4.0   
1                  3.0                     7.0                   4.0   
2                  3.0                     7.0                   4.0   
3                  5.0                     4.0                   4.0   
4                  6.0                     4.0                   4.0   

   Credit_Utilization_Ratio  Credit_History_Age  Payment_of_Min_Amount  \
0                 26.822620               265.0                      1   
1                 31.944960               265.0                      1   
2                 28.609352               267.0                      1   
3                 31.377862               268.0                      1   
4                 24.797347               269.0                      1   

   Amount_invested_monthly  Monthly_Balance  Credit_Score  Credit_Mix  ...  \
0                80.415295       312.494089             0           1  ...   
1               118.280222       284.629162             0           1  ...   
2                81.699521       331.209863             0           1  ...   
3               199.458074       223.451310             0           1  ...   
4                41.420153       341.489231             0           1  ...   

    Age  Annual_Income  Num_Bank_Accounts  Num_Credit_Card  Interest_Rate  \
0  23.0       19114.12                3.0              4.0            3.0   
1  23.0       19114.12                3.0              4.0            3.0   
2  23.0       19114.12                3.0              4.0            3.0   
3  23.0       19114.12                3.0              4.0            3.0   
4  23.0       19114.12                3.0              4.0            3.0   

   Num_of_Loan  Monthly_Inhand_Salary  Changed_Credit_Limit  Outstanding_Debt  \
0          4.0            1824.843333                 11.27            809.98   
1          4.0            1824.843333                 11.27            809.98   
2          4.0            1824.843333                 11.27            809.98   
3          4.0            1824.843333                 11.27            809.98   
4          4.0            1824.843333                 11.27            809.98   

   Total_EMI_per_month  
0            49.574949  
1            49.574949  
2            49.574949  
3            49.574949  
4            49.574949  

[5 rows x 21 columns]

In [11]:
x=df.drop(['Credit_Score'],axis=1)
y=df['Credit_Score']

In [26]:
import imblearn
from imblearn.over_sampling import RandomOverSampler
ros=RandomOverSampler()
x_sam,y_sam=ros.fit_resample(x,y)

In [27]:
print('Previous count:',y.value_counts())
print('Original count:',y_sam.value_counts())

Previous count: 2    53149
1    28988
0    17823
Name: Credit_Score, dtype: int64
Original count: 0    53149
2    53149
1    53149
Name: Credit_Score, dtype: int64


In [28]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test=train_test_split(x_sam, y_sam, test_size=0.20, random_state=42)
print(x_train.shape, x_test.shape, y_train.shape, y_test.shape)

(127557, 20) (31890, 20) (127557,) (31890,)


In [29]:
from sklearn.tree import DecisionTreeClassifier
dtree=DecisionTreeClassifier(criterion='gini')
dtree.fit(x_train,y_train)

DecisionTreeClassifier()

In [30]:
y_pred_train=dtree.predict(x_train)
y_pred_test=dtree.predict(x_test)

In [31]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

In [32]:
print('Training report:',classification_report(y_train,y_pred_train))
print('Test report:',classification_report(y_test,y_pred_test))

Training report:               precision    recall  f1-score   support

           0       1.00      1.00      1.00     42282
           1       1.00      1.00      1.00     42717
           2       1.00      1.00      1.00     42558

    accuracy                           1.00    127557
   macro avg       1.00      1.00      1.00    127557
weighted avg       1.00      1.00      1.00    127557

Test report:               precision    recall  f1-score   support

           0       0.90      0.97      0.93     10867
           1       0.87      0.92      0.89     10432
           2       0.88      0.75      0.81     10591

    accuracy                           0.88     31890
   macro avg       0.88      0.88      0.88     31890
weighted avg       0.88      0.88      0.88     31890



In [33]:
print('Training confusion report:',confusion_matrix(y_train,y_pred_train))
print('Test confusion report:',confusion_matrix(y_test,y_pred_test))

Training confusion report: [[42282     0     0]
 [    0 42717     0]
 [    0     0 42558]]
Test confusion report: [[10570    16   281]
 [   36  9599   797]
 [ 1150  1467  7974]]


In [34]:
print('Training accuracy:',accuracy_score(y_train,y_pred_train))
print('Test accuracy:',accuracy_score(y_test,y_pred_test))

Training accuracy: 1.0
Test accuracy: 0.8825023518344308


In [35]:
from sklearn.model_selection import cross_val_score
cvs=cross_val_score(dtree,x_train,y_train,cv=10)
print('10 training accuracy is :',cvs)
print('Avg training accuracy is :',cvs.mean())
print('Max training accuracy is :',cvs.max())

10 training accuracy is : [0.87511759 0.8736281  0.87872374 0.87096268 0.87590154 0.87370649
 0.87300094 0.87150137 0.87228538 0.87785182]
Avg training accuracy is : 0.8742679651816644
Max training accuracy is : 0.8787237378488555


In [36]:
dtree.feature_importances_

array([0.06517561, 0.03669188, 0.02217264, 0.05025516, 0.08243232,
       0.00500569, 0.0499578 , 0.04882886, 0.1381269 , 0.01163694,
       0.02924411, 0.03184112, 0.01970802, 0.02132258, 0.04586416,
       0.01036682, 0.02697047, 0.05215011, 0.21723065, 0.03501816])

In [37]:
pd.DataFrame(index=x.columns,data=dtree.feature_importances_,columns=['Feature Importance'])

Feature Importance
Delay_from_due_date                 0.065176
Num_of_Delayed_Payment              0.036692
Num_Credit_Inquiries                0.022173
Credit_Utilization_Ratio            0.050255
Credit_History_Age                  0.082432
Payment_of_Min_Amount               0.005006
Amount_invested_monthly             0.049958
Monthly_Balance                     0.048829
Credit_Mix                          0.138127
Payment_Behaviour                   0.011637
Age                                 0.029244
Annual_Income                       0.031841
Num_Bank_Accounts                   0.019708
Num_Credit_Card                     0.021323
Interest_Rate                       0.045864
Num_of_Loan                         0.010367
Monthly_Inhand_Salary               0.026970
Changed_Credit_Limit                0.052150
Outstanding_Debt                    0.217231
Total_EMI_per_month                 0.035018